name: Build & Test

on:
  schedule:
    - cron: "49 2 * * 1"
  workflow_dispatch:

jobs:
  tests:
    name: Tests
    uses: swift-libp2p/swift-libp2p-queues-redis-driver/.github/workflows/pull_request.yml@main
